ignoreScripts: true
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - "@vercel/cli-config@0.3.1"
  - "@vercel/cli-exec@1.0.1"
  - "@vercel/functions@3.9.11"
  - "@vercel/oidc@4.0.0"
  - "prisma@7.10.0"
  - "rollup@2.80.0"
minimumReleaseAge: 1440
